import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    include: [
      'test/ack-peer-selection.test.ts',
      'test/trust-metadata.test.ts',
      'test/dkg-publisher-compat.test.ts',
      'test/shared-memory-publish-boundary.test.ts',
      'test/storage-ack-roster-and-verify-mofn-extra.test.ts',
      'test/verification-metadata.test.ts',
      'test/verify-collector.test.ts',
      'test/verify-proposal-handler.test.ts',
      'test/views-min-trust-extra.test.ts',
      'test/async-lift-validation.test.ts',
      'test/async-lift-ka-broadcast-progress.test.ts',
      'test/async-lift-publish-options.test.ts',
      'test/async-promote-queue.test.ts',
      'test/lift-job-types.test.ts',
      'test/multi-root-token-rows.test.ts',
      'test/access-verification.test.ts',
      'test/promote-step-tag.test.ts',
      'test/ka-graph-skolemization.test.ts',
      'test/ka-graph-workspace-snapshot.test.ts',
      'test/ka-graph-workspace-receiver.test.ts',
      'test/ka-graph-finalization-storage.test.ts',
      'test/ka-graph-publish-storage.test.ts',
      'test/ka-graph-publish-ack.test.ts',
      'test/ka-graph-publish-handler.test.ts',
      'test/ka-graph-update-ack.test.ts',
      'test/ka-graph-update-handler.test.ts',
      'test/ka-graph-private-only-publish.test.ts',
      'test/agents-meta-bound.test.ts',
      'test/ack-collector.test.ts',
      'test/publish-lifecycle-logger.test.ts',
      'test/storage-ack-handler.test.ts',
      'test/swm-slice-ack-unbounded.test.ts',
    ],
    testTimeout: 60_000,
    maxWorkers: 1,
  },
});
