import { defineConfig } from "vitest/config";

import { RFC64_UNIT_TESTS } from "./vitest.rfc64-unit-tests";

// generic-sql-source.test.ts uses `import('node:sqlite')`, which is
// `--experimental-sqlite`-gated on Node 22.5–23.x. The flag is a
// process-level toggle, so mirror `vitest.config.ts`: switch to the
// `forks` pool and pass execArgv there. See the long comment in
// `vitest.config.ts` for the full rationale.
const SQLITE_EXEC_ARGV = [
  "--experimental-sqlite",
  "--no-warnings=ExperimentalWarning",
];

export default defineConfig({
  test: {
    include: [
      ...RFC64_UNIT_TESTS,
      "test/endorse.test.ts",
      "test/ack-candidate-pool.test.ts",
      "test/e2e-dht-dial.test.ts",
      "test/generic-sql-source.test.ts",
      "test/imported-artifact.test.ts",
      "test/publish-finalized-agent-lane.test.ts",
      "test/publish-foreign-author-resolution.test.ts",
      "test/durable-integrity-seal-assertion-version.test.ts",
      "test/iri-term.test.ts",
      "test/promote-async-default-agent.test.ts",
      "test/clear-promote-async-facade.test.ts",
      "test/query-min-trust-alias.test.ts",
      "test/query-source-labels.test.ts",
      "test/query-source-coverage.test.ts",
      "test/context-graph-on-chain-id-source-labels.test.ts",
      "test/confirmed-meta-source-labels.test.ts",
      "test/sync-envelope-cursor.test.ts",
      "test/w2-ual-parity.test.ts",
      "test/rfc64-receiver-admission-deferral.test.ts",
      "test/rfc64-precommit-owner-attribution.test.ts",
      "test/exact-assets.test.ts",
      "test/exact-asset-responder.test.ts",
      "test/exact-asset-wire-parse.test.ts",
      "test/swm/host-catchup-sign.test.ts",
      "test/swm/host-catchup-wire.test.ts",
      "test/swm/host-mode-store.test.ts",
      "test/swm/host-mode-key-canonicalization.test.ts",
      "test/rs-heal-stranded-kc-decorated.test.ts",
      "test/vm-reconcile-source-labels.test.ts",
      "test/profile-fix-verify.test.ts",
      "test/pca-v10-facade.test.ts",
      "test/ensure-registered-for-publish.test.ts",
      "test/sync-verify-collapsed.test.ts",
      "test/sync-verify-rootless.test.ts",
      "test/sync-control-metadata-admission.test.ts",
      "test/sync-durable-worker-wire.test.ts",
      "test/changelog-requester.test.ts",
      "test/durable-sync-since-threading.test.ts",
      "test/durable-sync-budget.test.ts",
      "test/durable-sync-graph-scoped-materialization.test.ts",
      "test/durable-sync-lifecycle-binding.test.ts",
      "test/durable-progress.test.ts",
      "test/gossip-publish-handler.test.ts",
      "test/discovery-subscription-boundary.test.ts",
      "test/core-fills-gap.test.ts",
      "test/swm-late-joiner-deferred-gossip.test.ts",
      "test/swm-plaintext-oracle-wiring.test.ts",
      "test/oversize-filter.test.ts",
      "test/cg-registration-oversize-guard.test.ts",
      "test/sync-responder-concurrent-interleaving.test.ts",
      "test/durable-meta-admission.test.ts",
      "test/sync-responder-log-volume.test.ts",
      "test/sync-responder-snapshot-cache.test.ts",
      "test/sync-responder-durable-meta-subject-atomic.test.ts",
      "test/sync-responder-cursor.test.ts",
      "test/sync-responder-oversized-fallback.test.ts",
      "test/sync-responder-swm-meta-ceiling.test.ts",
      "test/sync-responder-large-graph-stack-overflow.test.ts",
      "test/sync-page-frame-budget.test.ts",
      "test/sync-byte-budget-pages.test.ts",
      "test/sync-append-in-place.test.ts",
      "test/sync-memory-metrics.test.ts",
      "test/sync-responder-metrics.test.ts",
      "test/sync-transport-metrics.test.ts",
      "test/sync-attempt-telemetry.test.ts",
      "test/sync-operation-telemetry.test.ts",
      "test/sync-fetch-coalescing.test.ts",
      "test/sync-fetch-coalescing-durable.test.ts",
      "test/sync-backpressure.test.ts",
      "test/sync-policy.test.ts",
      "test/catchup-policy.test.ts",
      "test/catchup-concurrency.test.ts",
      // #2050 — the stop rule for the bounded repeat of the public SWM peer walk.
      "test/catchup-pass-policy.test.ts",
      "test/map-with-concurrency.test.ts",
      "test/peer-selection.test.ts",
      "test/sync-requester-priority.test.ts",
      "test/sync-requester-progress.test.ts",
      "test/rootless-durable-bounded-progress.test.ts",
      "test/rootless-durable-skips-legacy-partition.test.ts",
      "test/rootless-lifecycle-graph.test.ts",
      "test/swm-recovery.test.ts",
      "test/dkg-agent-snapshot-store-injection.test.ts",
      "test/swm-snapshot-sync.test.ts",
      "test/sync-responder-protection.test.ts",
      "test/sync-on-connect-retry.test.ts",
      "test/sync-on-connect-churn.test.ts",
      "test/system-context-graph-policy.test.ts",
      "test/sync-requester-bailout.test.ts",
      "test/swm-catchup-peer-selection.test.ts",
      "test/swm-curator-recovery-plan.test.ts",
      "test/swm-fanout-peer-selection.test.ts",
      "test/publish-literal-size.test.ts",
      "test/verify-batch.test.ts",
      "test/chain-cursor-wiring.test.ts",
      "test/chain-reconciler.test.ts",
      "test/core-fills-gap.test.ts",
      "test/finalization-reconcile-negative-memo.test.ts",
      "test/startup-jitter.test.ts",
      "test/finalization-lifecycle-logger.test.ts",
      "test/finalization-handler.test.ts",
      "test/finalization-handler-chain-truth.test.ts",
      "test/finalization-handler-defensive-cg-id.test.ts",
      "test/finalization-recovery.test.ts",
      "test/finalization-recovery-worker.test.ts",
      "test/finalization-recovery-sqlite-deferred.test.ts",
      "test/finalization-recovery-sqlite-migration.test.ts",
      "test/finalization-recovery-sqlite-store.test.ts",
      "test/named-ka-publish-recovery.test.ts",
      "test/ka-graph-finalization-handler.test.ts",
      "test/swm-slice-ka-bound.test.ts",
      "test/ka-lifecycle-asset-ual-timeout.test.ts",
      "test/storage-ack-lifecycle-identity.test.ts",
      "test/v10-ack-provider-wiring.test.ts",
      "test/direct-rootless-publish.test.ts",
      "test/rootless-update-boundary.test.ts",
      "test/rootless-update-error.test.ts",
      "test/changelog-requester.test.ts",
      "test/encrypt-inline-policy.test.ts",
      "test/queued-publish-options.test.ts",
      "test/agents-meta-policy.test.ts",
      "test/agents-meta-sync-wiring.test.ts",
      "test/network-identity-proof.test.ts",
      "test/network-admission-probe-retry.test.ts",
      "test/network-admission.test.ts",
      "test/network-admission-coordinator.test.ts",
      "test/explicit-connect-admission.test.ts",
      "test/sync-responder-agents-meta-serve-skip.test.ts",
      "test/messenger-substrate.test.ts",
      "test/context-graph-join-policy.test.ts",
      "test/context-graph-list-concurrency.test.ts",
      "test/cg-resolve-refresh.test.ts",
      "test/private-cg-membership-bootstrap.test.ts",
      "test/workspace-crypto-delegatee-filter.test.ts",
      "test/swm-public-snapshot-materialization.test.ts",
      "test/swm-public-cg-plaintext.test.ts",
      "test/swm-snapshot-materializer.test.ts",
      // #2079 — the already-materialized witness: the warm-path win, the count
      // gate that keeps it self-healing, and the digest binding that makes an
      // equal-count version change safe.
      "test/swm-materialization-witness.test.ts",
      "test/replace-subject-agent-wrapper.test.ts",
    ],
    testTimeout: 60_000,
    maxWorkers: 1,
    pool: "forks",
    execArgv: SQLITE_EXEC_ARGV,
  },
});
