import { defineConfig } from "vitest/config";

// generic-sql-source.test.ts uses `import('node:sqlite')`, which is
// `--experimental-sqlite`-gated on Node 22.5–23.x. The flag is a
// process-level toggle, so mirror `vitest.config.ts`: switch to the
// `forks` pool and pass execArgv there. See the long comment in
// `vitest.config.ts` for the full rationale.
const SQLITE_EXEC_ARGV = [
  "--experimental-sqlite",
  "--no-warnings=ExperimentalWarning",
];

export default defineConfig({
  test: {
    include: [
      "test/agent-message-manifest.test.ts",
      "test/endorse.test.ts",
      "test/ack-candidate-pool.test.ts",
      "test/e2e-dht-dial.test.ts",
      "test/generic-sql-source.test.ts",
      "test/imported-artifact.test.ts",
      "test/publish-finalized-agent-lane.test.ts",
      "test/promote-async-default-agent.test.ts",
      "test/query-min-trust-alias.test.ts",
      "test/sync-envelope-cursor.test.ts",
      "test/swm/host-catchup-sign.test.ts",
      "test/swm/host-catchup-wire.test.ts",
      "test/swm/host-mode-store.test.ts",
      "test/swm/host-mode-key-canonicalization.test.ts",
      "test/profile-fix-verify.test.ts",
      "test/pca-v10-facade.test.ts",
      "test/ensure-registered-for-publish.test.ts",
      "test/sync-verify-collapsed.test.ts",
      "test/sync-verify-rootless.test.ts",
      "test/sync-control-metadata-admission.test.ts",
      "test/sync-durable-worker-wire.test.ts",
      "test/changelog-requester.test.ts",
      "test/durable-sync-since-threading.test.ts",
      "test/durable-sync-graph-scoped-materialization.test.ts",
      "test/durable-progress.test.ts",
      "test/gossip-publish-handler.test.ts",
      "test/discovery-subscription-boundary.test.ts",
      "test/core-fills-gap.test.ts",
      "test/swm-late-joiner-deferred-gossip.test.ts",
      "test/oversize-filter.test.ts",
      "test/cg-registration-oversize-guard.test.ts",
      "test/sync-responder-concurrent-interleaving.test.ts",
      "test/durable-meta-admission.test.ts",
      "test/sync-responder-log-volume.test.ts",
      "test/sync-responder-snapshot-cache.test.ts",
      "test/sync-responder-cursor.test.ts",
      "test/sync-responder-oversized-fallback.test.ts",
      "test/sync-responder-large-graph-stack-overflow.test.ts",
      "test/sync-page-frame-budget.test.ts",
      "test/sync-byte-budget-pages.test.ts",
      "test/sync-append-in-place.test.ts",
      "test/sync-memory-metrics.test.ts",
      "test/sync-responder-metrics.test.ts",
      "test/sync-fetch-coalescing.test.ts",
      "test/sync-backpressure.test.ts",
      "test/sync-requester-priority.test.ts",
      "test/sync-requester-progress.test.ts",
      "test/rootless-durable-bounded-progress.test.ts",
      "test/rootless-durable-skips-legacy-partition.test.ts",
      "test/rootless-lifecycle-graph.test.ts",
      "test/swm-recovery.test.ts",
      "test/swm-snapshot-sync.test.ts",
      "test/sync-responder-protection.test.ts",
      "test/sync-on-connect-retry.test.ts",
      "test/sync-on-connect-churn.test.ts",
      "test/sync-requester-bailout.test.ts",
      "test/swm-catchup-peer-selection.test.ts",
      "test/swm-fanout-peer-selection.test.ts",
      "test/publish-literal-size.test.ts",
      "test/verify-batch.test.ts",
      "test/chain-cursor-wiring.test.ts",
      "test/chain-reconciler.test.ts",
      "test/core-fills-gap.test.ts",
      "test/finalization-reconcile-negative-memo.test.ts",
      "test/startup-jitter.test.ts",
      "test/finalization-lifecycle-logger.test.ts",
      "test/ka-graph-finalization-handler.test.ts",
      "test/swm-slice-ka-bound.test.ts",
      "test/ka-lifecycle-asset-ual-timeout.test.ts",
      "test/storage-ack-lifecycle-identity.test.ts",
      "test/v10-ack-provider-wiring.test.ts",
      "test/direct-rootless-publish.test.ts",
      "test/rootless-update-boundary.test.ts",
      "test/rootless-update-error.test.ts",
      "test/changelog-requester.test.ts",
      "test/encrypt-inline-policy.test.ts",
      "test/queued-publish-options.test.ts",
      "test/agents-meta-policy.test.ts",
      "test/agents-meta-sync-wiring.test.ts",
      "test/network-identity-proof.test.ts",
      "test/network-admission-probe-retry.test.ts",
      "test/network-admission.test.ts",
      "test/network-admission-coordinator.test.ts",
      "test/explicit-connect-admission.test.ts",
      "test/sync-responder-agents-meta-serve-skip.test.ts",
      "test/messenger-substrate.test.ts",
      "test/context-graph-join-policy.test.ts",
      "test/context-graph-list-concurrency.test.ts",
      "test/cg-resolve-refresh.test.ts",
      "test/private-cg-membership-bootstrap.test.ts",
      "test/workspace-crypto-delegatee-filter.test.ts",
    ],
    testTimeout: 60_000,
    maxWorkers: 1,
    pool: "forks",
    execArgv: SQLITE_EXEC_ARGV,
  },
});
