/**
 * Dormant system-record V1 protocol foundation.
 *
 * Kept off the broad core barrel so legacy/default-disabled node startup does not
 * eagerly load the protocol's cryptographic and canonical-codec dependency graph.
 */
export {
  SYSTEM_RECORD_APPLY_TIMEOUT_MS,
  SYSTEM_RECORD_AUTHORITY_SEQUENCE_MAX,
  SYSTEM_RECORD_CONTINUATION_TIMEOUT_MS,
  SYSTEM_RECORD_DIGEST_DOMAINS_V1,
  SYSTEM_RECORD_ED25519_PUBLIC_KEY_BYTES,
  SYSTEM_RECORD_ED25519_SIGNATURE_BYTES,
  SYSTEM_RECORD_EIP191_MAX_S,
  SYSTEM_RECORD_EIP191_SIGNATURE_BYTES,
  SYSTEM_RECORD_INSPECTION_TIMEOUT_MS,
  SYSTEM_RECORD_INTERNAL_MAX_ENTRIES,
  SYSTEM_RECORD_INTERNAL_MIN_ENTRIES,
  SYSTEM_RECORD_INTERNAL_TARGET_BYTES,
  SYSTEM_RECORD_INVENTORY_ROW_VERSION,
  SYSTEM_RECORD_KIND_V1,
  SYSTEM_RECORD_LEAF_MAX_ROWS,
  SYSTEM_RECORD_LEAF_MIN_ROWS,
  SYSTEM_RECORD_LEAF_TARGET_BYTES,
  SYSTEM_RECORD_MATERIALIZER_HARD_TIMEOUT_MS,
  SYSTEM_RECORD_MATERIALIZER_HEALTHY_P99_MS,
  SYSTEM_RECORD_MAX_ACTIVATION_BUNDLE_BYTES,
  SYSTEM_RECORD_MAX_ACTIVATION_CLOSURE_BYTES,
  SYSTEM_RECORD_MAX_ACTIVATION_INVENTORY_LEAVES,
  SYSTEM_RECORD_MAX_ACTIVATION_METADATA_BYTES,
  SYSTEM_RECORD_MAX_ACTIVATION_RECORDS,
  SYSTEM_RECORD_MAX_ACTIVATION_REFERENCES,
  SYSTEM_RECORD_MAX_ADVERTISED_CLOSURE_BYTES,
  SYSTEM_RECORD_MAX_ADVERTISED_CLOSURE_OBJECTS,
  SYSTEM_RECORD_MAX_ADVERTISED_CLOSURE_REFERENCES,
  SYSTEM_RECORD_MAX_APPLIED_AGGREGATE_BYTES,
  SYSTEM_RECORD_MAX_APPLIED_AGGREGATE_QUADS,
  SYSTEM_RECORD_MAX_APPLIED_STATE_BYTES,
  SYSTEM_RECORD_MAX_ARRAY_JSON_DEPTH,
  SYSTEM_RECORD_MAX_ATOMIC_BUNDLE_BYTES,
  SYSTEM_RECORD_MAX_ATOMIC_DECODED_TERM_BYTES,
  SYSTEM_RECORD_MAX_ATOMIC_INSPECTION_RESPONSE_BYTES,
  SYSTEM_RECORD_MAX_ATOMIC_PREPARED_BYTES,
  SYSTEM_RECORD_MAX_ATOMIC_RESERVED_INSPECTION_RESPONSE_BYTES,
  SYSTEM_RECORD_MAX_ATOMIC_SIGNED_HEAD_BYTES,
  SYSTEM_RECORD_MAX_ATOMIC_SPARQL_REQUEST_BYTES,
  SYSTEM_RECORD_MAX_ATOMIC_TRANSIENT_BYTES,
  SYSTEM_RECORD_MAX_BUNDLE_DECODE_CONCURRENCY,
  SYSTEM_RECORD_MAX_CACHE_LIVE_METADATA_BYTES,
  SYSTEM_RECORD_MAX_CACHE_RESERVE_METADATA_BYTES,
  SYSTEM_RECORD_MAX_CACHE_STAGING_BYTES,
  SYSTEM_RECORD_MAX_CLOCK_SKEW_MS,
  SYSTEM_RECORD_MAX_CLOSURE_BYTES,
  SYSTEM_RECORD_MAX_CLOSURE_OBJECTS,
  SYSTEM_RECORD_MAX_CLOSURE_SIDECAR_LIVE_METADATA_BYTES,
  SYSTEM_RECORD_MAX_COMPLETED_LEAF_BYTES,
  SYSTEM_RECORD_MAX_COMPLETED_LEAF_DIGESTS,
  SYSTEM_RECORD_MAX_CONFLICT_DIGESTS,
  SYSTEM_RECORD_MAX_CONFLICT_ENTRIES,
  SYSTEM_RECORD_MAX_CONFLICT_SIDECAR_AGGREGATE_BYTES,
  SYSTEM_RECORD_MAX_CONFLICT_SIDECAR_METADATA_BYTES,
  SYSTEM_RECORD_MAX_CONFLICT_SIDECAR_REFERENCES,
  SYSTEM_RECORD_MAX_CONFLICT_SIDECARS,
  SYSTEM_RECORD_MAX_CONTINUATION_ADVANCES,
  SYSTEM_RECORD_MAX_CONTINUATION_CLOSURE_WIRE_BYTES,
  SYSTEM_RECORD_MAX_CONTINUATION_SLICES,
  SYSTEM_RECORD_MAX_CONTINUATION_WIRE_BYTES,
  SYSTEM_RECORD_MAX_DIRTY_RECORDS,
  SYSTEM_RECORD_MAX_DIRTY_STATE_BYTES,
  SYSTEM_RECORD_MAX_EIP1271_CACHE_ENTRIES,
  SYSTEM_RECORD_MAX_EIP1271_CALLS_PER_SLICE,
  SYSTEM_RECORD_MAX_EIP1271_CONCURRENCY,
  SYSTEM_RECORD_MAX_EIP1271_SIGNATURE_BYTES,
  SYSTEM_RECORD_MAX_EVIDENCE_ROW_BYTES,
  SYSTEM_RECORD_MAX_EXACT_FETCH_WAITERS,
  SYSTEM_RECORD_MAX_FLAT_JSON_DEPTH,
  SYSTEM_RECORD_MAX_FRAME_BYTES,
  SYSTEM_RECORD_MAX_FRAME_PAYLOAD_BYTES,
  SYSTEM_RECORD_MAX_HEADER_BYTES,
  SYSTEM_RECORD_MAX_INTERNAL_ENTRY_BYTES,
  SYSTEM_RECORD_MAX_INVENTORY_CHILD_INDEX,
  SYSTEM_RECORD_MAX_INVENTORY_INTERNAL_JSON_DEPTH,
  SYSTEM_RECORD_MAX_INVENTORY_LEAVES,
  SYSTEM_RECORD_MAX_INVENTORY_OBJECTS,
  SYSTEM_RECORD_MAX_INVENTORY_PATH_DEPTH,
  SYSTEM_RECORD_MAX_INVENTORY_RECORDS,
  SYSTEM_RECORD_MAX_JSON_DEPTH,
  SYSTEM_RECORD_MAX_MATERIALIZER_WRITE_CONCURRENCY,
  SYSTEM_RECORD_MAX_OBJECT_CACHE_BYTES,
  SYSTEM_RECORD_MAX_OBJECT_CACHE_OBJECTS,
  SYSTEM_RECORD_MAX_ORDINARY_ROW_BYTES,
  SYSTEM_RECORD_MAX_OWNED_SUBJECTS,
  SYSTEM_RECORD_MAX_PEER_ID_BYTES,
  SYSTEM_RECORD_MAX_PENDING_EXACT_FETCHES,
  SYSTEM_RECORD_MAX_PROJECTION_BYTES,
  SYSTEM_RECORD_MAX_PROJECTION_QUADS,
  SYSTEM_RECORD_MAX_PROVIDER_CONTINUATION_BYTES,
  SYSTEM_RECORD_MAX_PROVIDER_CONTINUATIONS,
  SYSTEM_RECORD_MAX_PUBLICATION_JOURNAL_BYTES,
  SYSTEM_RECORD_MAX_PUBLICATION_JOURNAL_REFERENCES,
  SYSTEM_RECORD_MAX_RECLAIM_BYTES,
  SYSTEM_RECORD_MAX_RECLAIM_DELETES,
  SYSTEM_RECORD_MAX_RESOLVED_FORK_TUPLES,
  SYSTEM_RECORD_MAX_RESTART_VALIDATION_BYTES,
  SYSTEM_RECORD_MAX_RESTART_VALIDATION_KEYS,
  SYSTEM_RECORD_MAX_ROOT_CLAIMS,
  SYSTEM_RECORD_MAX_ROW_BYTES,
  SYSTEM_RECORD_MAX_RUNTIME_ACCOUNTED_BYTES,
  SYSTEM_RECORD_MAX_RUNTIME_CONTROL_BYTES,
  SYSTEM_RECORD_MAX_RUNTIME_DECODE_BYTES,
  SYSTEM_RECORD_MAX_RUNTIME_EIP1271_BYTES,
  SYSTEM_RECORD_MAX_RUNTIME_HEAD_BYTES,
  SYSTEM_RECORD_MAX_RUNTIME_LEAF_BYTES,
  SYSTEM_RECORD_MAX_RUNTIME_ROOT_DIRECTORY_BYTES,
  SYSTEM_RECORD_MAX_SERVE_PINS,
  SYSTEM_RECORD_MAX_SHALLOW_JSON_DEPTH,
  SYSTEM_RECORD_MAX_SIDECAR_BYTES,
  SYSTEM_RECORD_MAX_SIDECAR_OBJECTS,
  SYSTEM_RECORD_MAX_SIGNED_CONTROL_JSON_DEPTH,
  SYSTEM_RECORD_MAX_SIGNED_HEAD_JSON_DEPTH,
  SYSTEM_RECORD_MAX_SLICE_ADVANCES,
  SYSTEM_RECORD_MAX_SLICE_REQUESTS,
  SYSTEM_RECORD_MAX_SLICE_RETRIES_PER_REQUEST,
  SYSTEM_RECORD_MAX_SLICE_WIRE_BYTES,
  SYSTEM_RECORD_MAX_STATUS_BYTES,
  SYSTEM_RECORD_MAX_STATUS_ROWS,
  SYSTEM_RECORD_MAX_TREE_HEIGHT,
  SYSTEM_RECORD_MAX_TREE_UPDATE_BYTES,
  SYSTEM_RECORD_MAX_TREE_UPDATE_OBJECTS,
  SYSTEM_RECORD_MAX_TUPLE_JSON_DEPTH,
  SYSTEM_RECORD_MAX_UNREFERENCED_BYTES,
  SYSTEM_RECORD_MAX_UNREFERENCED_OBJECTS,
  SYSTEM_RECORD_MAX_WIRE_REQUEST_JSON_DEPTH,
  SYSTEM_RECORD_OBJECT_CAPS_V1,
  SYSTEM_RECORD_PROTOCOL_V1,
  SYSTEM_RECORD_PROVIDER_EXCHANGE_TIMEOUT_MS,
  SYSTEM_RECORD_PROVIDER_REQUEST_TOKEN_CAPACITY,
  SYSTEM_RECORD_PROVIDER_REQUEST_TOKEN_REFILL_PER_MINUTE,
  SYSTEM_RECORD_PROVIDER_RESPONSE_TOKEN_CAPACITY,
  SYSTEM_RECORD_PROVIDER_RESPONSE_TOKEN_REFILL_PER_MINUTE,
  SYSTEM_RECORD_RECLAIM_TIMEOUT_MS,
  SYSTEM_RECORD_REPAIR_MIN_DISPATCH_BUDGET_MS,
  SYSTEM_RECORD_REQUIRED_DISPATCH_BUDGET_MS,
  SYSTEM_RECORD_ROOT_MAX_ENTRIES,
  SYSTEM_RECORD_ROOT_MIN_ENTRIES,
  SYSTEM_RECORD_SERVE_PIN_TIMEOUT_MS,
  SYSTEM_RECORD_SIGNATURE_DOMAINS_V1,
  SYSTEM_RECORD_SLICE_TIMEOUT_MS,
  SYSTEM_RECORD_STATUS_TIMEOUT_MS,
  SYSTEM_RECORD_WIRE_VERSION_V1,
  type SystemRecordObjectKindV1,
} from './system-record-limits-v1.js';

export {
  AGENT_PROFILE_LINK_PREDICATES_V1,
  AGENT_PROFILE_SCHEMA_TERMS_V1,
  assertAgentProfileAuthorityTransitionV1,
  assertAgentProfileConflictEvidenceV1,
  assertAgentProfileForkResolutionEvidenceV1,
  assertAgentProfileForkResolutionV1,
  assertAgentProfileHeadObjectV1,
  assertAgentProfileVerifiedAuthoritySummaryV1,
  assertAgentRootV1,
  assertCanonicalEip191SignatureV1,
  assertCanonicalRfc3339SecondsV1,
  assertCanonicalSystemRecordPeerIdV1,
  assertDerivedAgentEncryptionSubjectV1,
  assertOwnedSubjectTableObjectV1,
  assertSignedAgentProfileAuthorityTransitionEnvelopeV1,
  assertSignedAgentProfileForkResolutionEnvelopeV1,
  assertSignedAgentProfileHeadEnvelopeV1,
  assertSystemRecordClosureAlgebraV1,
  assertSystemRecordPeerBindingV1,
  buildAgentProfileVerificationClosureV1,
  buildSystemRecordSignatureMessageV1,
  canonicalizeAgentProfileAuthorityTransitionV1,
  canonicalizeAgentProfileConflictEvidenceV1,
  canonicalizeAgentProfileForkResolutionV1,
  canonicalizeAgentProfileHeadObjectV1,
  canonicalizeOwnedSubjectTableObjectV1,
  canonicalizeSignedSystemRecordEnvelopeV1,
  canonicalizeSystemRecordRootCollisionEvidenceV1,
  classifyAgentProfileOwnedSubjectV1,
  computeAgentProfileAuthorityTransitionDigestV1,
  computeAgentProfileConflictEvidenceDigestV1,
  computeAgentProfileForkResolutionDigestV1,
  computeAgentProfileHeadObjectDigestV1,
  computeOwnedSubjectTableDigestV1,
  computeSignedSystemRecordEnvelopeDigestV1,
  computeSystemRecordRootCollisionEvidenceDigestV1,
  copyBoundedSystemRecordBytesV1,
  createSystemRecordCacheMetadataV1,
  createSystemRecordCacheReferenceV1,
  decodeUnpaddedBase64UrlV1,
  deriveAgentProfileOwnedSubjectV1,
  digestSystemRecordBytesV1,
  digestSystemRecordJsonV1,
  eip191PersonalMessageHashV1,
  EMPTY_OWNED_SUBJECT_TABLE_DIGEST_V1,
  evaluateAgentProfileHeadAdvanceV1,
  evaluateAuthorityTransitionAgainstAcceptedStateV1,
  evaluateAuthorityTransitionConflictV1,
  evaluateAuthorityTransitionV1,
  isAgentProfileHeadBoundToAcceptedTransitionV1,
  isAllowedAgentProfilePredicateV1,
  isDirectResolvingSuccessorV1,
  parseCanonicalAgentProfileAuthorityTransitionV1,
  parseCanonicalAgentProfileConflictEvidenceV1,
  parseCanonicalAgentProfileForkResolutionV1,
  parseCanonicalAgentProfileHeadObjectV1,
  parseCanonicalOwnedSubjectTableObjectV1,
  parseCanonicalRfc3339SecondsV1,
  parseCanonicalSignedAgentProfileAuthorityTransitionEnvelopeV1,
  parseCanonicalSignedAgentProfileForkResolutionEnvelopeV1,
  parseCanonicalSignedAgentProfileHeadEnvelopeV1,
  preflightSystemRecordCacheAccountingV1,
  recoverEip191SignerV1,
  SystemRecordObjectErrorV1,
  verifySignedSystemRecordEnvelopeV1,
  type AgentProfileAcceptedAuthorityStateV1,
  type AgentProfileActiveHeadObjectV1,
  type AgentProfileAppliedTransitionV1,
  type AgentProfileAuthorityTransitionV1,
  type AgentProfileClosureVerifierV1,
  type AgentProfileConflictEvidenceV1,
  type AgentProfileExactLinkedSubjectKindV1,
  type AgentProfileForkConflictEntryV1,
  type AgentProfileForkResolutionV1,
  type AgentProfileHeadAdvanceEvidenceV1,
  type AgentProfileHeadCommonV1,
  type AgentProfileHeadObjectV1,
  type AgentProfileIndexedSubjectKindV1,
  type AgentProfileLinkedSubjectKindV1,
  type AgentProfileOwnedSubjectKindV1,
  type AgentProfileTombstoneHeadObjectV1,
  type AgentProfileTransitionConflictEntryV1,
  type AgentProfileVerifiedAuthoritySummaryV1,
  type CanonicalRfc3339SecondsV1,
  type OwnedSubjectTableObjectV1,
  type SignedAgentProfileAuthorityTransitionEnvelopeV1,
  type SignedAgentProfileForkResolutionEnvelopeV1,
  type SignedAgentProfileHeadEnvelopeV1,
  type SignedSystemRecordEnvelopeV1,
  type SystemRecordAuthorityDecisionV1,
  type SystemRecordCacheMetadataV1,
  type SystemRecordCachePreflightInputV1,
  type SystemRecordCachePreflightResultV1,
  type SystemRecordCacheReferenceV1,
  type SystemRecordCacheRowAccountingV1,
  type SystemRecordClosureArtifactV1,
  type SystemRecordEip1271EvidenceV1,
  type SystemRecordNoSignatureEvidenceV1,
  type SystemRecordObjectErrorCodeV1,
  type SystemRecordPeerPublicKeyV1,
  type SystemRecordRootCollisionEvidenceV1,
  type SystemRecordSignatureEntryV1,
  type SystemRecordSignatureRoleV1,
  type SystemRecordSignatureSuiteV1,
  type SystemRecordVerificationClosureObjectV1,
  type SystemRecordVerificationClosureV1,
  type VerifySystemRecordEnvelopeOptionsV1,
} from './system-record-objects-v1.js';

export {
  agentProfileIdentityFactsV1,
  assertAgentProfileProjectionIdentityV1,
  assertAgentProfileProjectionSchemaV1,
  type AgentProfileIdentityFactsInputV1,
  type AgentProfileIdentityFactsV1,
  type AgentProfileIdentityFactV1,
  type AgentProfileProjectionQuadV1,
} from './agent-profile-projection-schema-v1.js';

export {
  assertSystemRecordAppliedStateV1,
  assertSystemRecordCapacityStateV1,
  assertSystemRecordMaterializationReceiptV1,
  assertSystemRecordRootClaimSetV1,
  canonicalizeSystemRecordAppliedStateV1,
  canonicalizeSystemRecordCapacityStateV1,
  canonicalizeSystemRecordMaterializationReceiptV1,
  canonicalizeSystemRecordRootClaimSetV1,
  computeSystemRecordAccountedBytesV1,
  computeSystemRecordAppliedStateDigestV1,
  computeSystemRecordCapacityStateDigestV1,
  computeSystemRecordMaterializationReceiptDigestV1,
  computeSystemRecordRootClaimSetDigestV1,
  parseCanonicalSystemRecordAppliedStateV1,
  parseCanonicalSystemRecordCapacityStateV1,
  parseCanonicalSystemRecordMaterializationReceiptV1,
  parseCanonicalSystemRecordRootClaimSetV1,
  SYSTEM_RECORD_EMPTY_PROJECTION_DIGEST_V1,
  systemRecordAppliedStateAbsentV1,
  type SystemRecordAppliedStateAbsentV1,
  type SystemRecordAppliedStatePresentV1,
  type SystemRecordAppliedStateV1,
  type SystemRecordAppliedStatusV1,
  type SystemRecordCapacityStateV1,
  type SystemRecordConflictIntentOperationV1,
  type SystemRecordMaterializationReceiptV1,
  type SystemRecordRootClaimSetV1,
} from './system-record-applied-state-v1.js';

export {
  assertSignedSystemRecordRootDescriptorEnvelopeV1,
  assertSystemRecordInventoryCowUpdateBoundV1,
  assertSystemRecordInventoryInternalObjectV1,
  assertSystemRecordInventoryLeafObjectV1,
  assertSystemRecordRootDescriptorObjectV1,
  buildSystemRecordInventoryTreeV1,
  buildSystemRecordProviderSignatureMessageV1,
  canonicalizeSignedSystemRecordRootDescriptorEnvelopeV1,
  canonicalizeSystemRecordInventoryInternalObjectV1,
  canonicalizeSystemRecordInventoryLeafObjectV1,
  canonicalizeSystemRecordRootDescriptorObjectV1,
  chooseSystemRecordByteAwareSplitIndexV1,
  chooseSystemRecordRebalanceV1,
  computeSystemRecordInventoryInternalDigestV1,
  computeSystemRecordInventoryLeafDigestV1,
  computeSystemRecordRootDescriptorDigestV1,
  computeSystemRecordStableKeyHashV1,
  createSystemRecordInventoryTraversalV1,
  decodeInventoryRowBase64UrlV1,
  decodeSystemRecordInventoryRowV1,
  encodeInventoryRowBase64UrlV1,
  encodeSystemRecordInventoryRowV1,
  parseCanonicalSignedSystemRecordRootDescriptorEnvelopeV1,
  parseCanonicalSystemRecordInventoryInternalObjectV1,
  parseCanonicalSystemRecordInventoryLeafObjectV1,
  parseCanonicalSystemRecordRootDescriptorObjectV1,
  SYSTEM_RECORD_INVENTORY_REBALANCE_TARGETS_V1,
  systemRecordInventoryRowMaxEncodedBytesV1,
  updateSystemRecordInventoryTreeV1,
  verifySignedSystemRecordRootDescriptorEnvelopeV1,
  type SignedSystemRecordRootDescriptorEnvelopeV1,
  type SystemRecordInventoryCowUpdateAccountingV1,
  type SystemRecordInventoryCowUpdateV1,
  type SystemRecordInventoryCowWriteV1,
  type SystemRecordInventoryInternalEntryV1,
  type SystemRecordInventoryInternalObjectV1,
  type SystemRecordInventoryLeafObjectV1,
  type SystemRecordInventoryLoadedObjectV1,
  type SystemRecordInventoryMutationV1,
  type SystemRecordInventoryObjectV1,
  type SystemRecordInventoryRejectedLoadV1,
  type SystemRecordInventoryRowV1,
  type SystemRecordInventoryStoredObjectV1,
  type SystemRecordInventoryTraversalSliceResultV1,
  type SystemRecordInventoryTraversalSliceV1,
  type SystemRecordInventoryTraversalV1,
  type SystemRecordInventoryTreeSnapshotV1,
  type SystemRecordRebalanceChoiceV1,
  type SystemRecordRootDescriptorObjectV1,
  type ValidatedSystemRecordInventoryTreeV1,
} from './system-record-inventory-v1.js';

export {
  decodeSystemRecordRequestFrameV1,
  decodeSystemRecordResponseFrameV1,
  decodeSystemRecordResponseHeaderV1,
  encodeSystemRecordRequestFrameV1,
  encodeSystemRecordResponseFrameV1,
  readSystemRecordHeaderLengthV1,
  verifySystemRecordResponsePayloadV1,
  type SystemRecordDecodedResponseFrameV1,
  type SystemRecordDecodedResponseHeaderV1,
  type SystemRecordErrorResponseHeaderV1,
  type SystemRecordGetBundleRequestV1,
  type SystemRecordGetControlObjectRequestV1,
  type SystemRecordGetInventoryObjectRequestV1,
  type SystemRecordGetRootRequestV1,
  type SystemRecordOkResponseHeaderV1,
  type SystemRecordRequestHeaderV1,
  type SystemRecordRequestOperationV1,
  type SystemRecordResponseHeaderV1,
  type SystemRecordResponseStatusV1,
} from './system-record-wire-v1.js';

export { assertNetworkIdV1, type NetworkIdV1 } from './sync-wire-identifiers.js';
export { assertCanonicalDigest, type Digest32V1 } from './sync-wire-scalars.js';
