import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { mergePackageCoverage } from '../merge-package-coverage.mjs';
import { checkPackageCoverage } from '../../ci/check-coverage.mjs';

test('shards merge hit maps, retain untouched source and enforce package floors', (t) => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'dkg-merge-coverage-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const directory = path.join(root, 'packages/core');
  fs.mkdirSync(path.join(directory, 'src'), { recursive: true });
  fs.mkdirSync(path.join(root, 'test-policy'));
  const span = (line) => ({ start: { line, column: 0 }, end: { line, column: 25 } });
  const file = 'packages/core/src/decision.ts';
  const untouched = 'packages/core/src/untouched.ts';
  fs.writeFileSync(path.join(root, file), 'export const a = 1;\nexport const b = 2;\n');
  fs.writeFileSync(path.join(root, untouched), 'export const c = 3;\n');
  const coverage = (filename, hits) => ({ path: filename, statementMap: Object.fromEntries(hits.map((_, i) => [i, span(i + 1)])), s: Object.fromEntries(hits.map((hit, i) => [i, hit])), fnMap: {}, f: {}, branchMap: {}, b: {} });
  const receipts = [[1, 0], [0, 1]].map((hits) => ({ package: 'core', coverage: { [file]: coverage(file, hits), [untouched]: coverage(untouched, [0]) } }));
  const map = mergePackageCoverage(root, 'core', receipts);
  assert.deepEqual(map.fileCoverageFor(path.join(root, file)).s, { 0: 1, 1: 1 });
  assert.equal(map.getCoverageSummary().lines.pct, 66.66);
  const lcov = fs.readFileSync(path.join(directory, 'coverage/lcov.info'), 'utf8');
  assert.match(lcov, /SF:src\/decision.ts\n/);
  const untouchedRecord = lcov.split('end_of_record').find((record) => record.includes('SF:src/untouched.ts\n'));
  assert.match(untouchedRecord, /^DA:1,0$/m);
  const policy = { packages: { core: { thresholds: { lines: 66, statements: 66, functions: 100, branches: 100 } } } };
  const writePolicy = () => fs.writeFileSync(path.join(root, 'test-policy/coverage-baselines.json'), JSON.stringify(policy));
  writePolicy();
  assert.equal(checkPackageCoverage('core', { root }).sourceFiles, 2);
  policy.packages.core.thresholds.lines = 67; writePolicy();
  assert.throws(() => checkPackageCoverage('core', { root }), /lines coverage.*below 67/);
  policy.packages.core.thresholds.lines = 66;
  policy.packages.core.preservedFiles = { 'src/untouched.ts': { lines: 1 } }; writePolicy();
  assert.throws(() => checkPackageCoverage('core', { root }), /preserved lines floor/);
  const escaped = [{ package: 'core', coverage: { 'packages/core/src/../../secret.ts': coverage('secret.ts', [1]) } }];
  assert.throws(() => mergePackageCoverage(root, 'core', escaped), /escaped production source/);
  assert.throws(() => mergePackageCoverage(root, 'core', []), /no coverage to merge/);
});
