// example-alerts.md as a first-class generated artifact: the WHOLE document
// is rendered from this template (rules table interpolated from the alert
// catalog), so render/--check treat it exactly like the JSON artifacts — no
// in-place mutation of a pre-existing file, no split source of truth.
import { alertDatasource } from './alerts.mjs';

// Markdown renderers for the alert specs (documentation concerns only — the
// Grafana payload derivation lives in alerts.mjs):
// - the summary table carries only plain-text fields; free-text cells are
//   pipe-escaped so a future title containing '|' cannot break the table
// - each query is emitted as its own FENCED code block (fence length adapts
//   to the longest backtick run), so no valid LogQL/PromQL is constrained by
//   GFM table escaping
const fenced = (t) => {
  const runs = t.match(/`+/g) ?? [];
  const fence = '`'.repeat(Math.max(3, ...runs.map(r => r.length + 1)));
  return `${fence}\n${t}\n${fence}`;
};
const mdCell = (t) => String(t).replaceAll('|', '\\|');
const rulesTable = (specs) => [
  '| # | Priority | Alert | Channel | Datasource | Fires when | for | noData |',
  '|---|---|---|---|---|---|---|---|',
  ...specs.map((s, i) =>
    `| ${i + 1} | **${s.priority}** | ${mdCell(s.title)} | #node-${s.signal} | ${alertDatasource(s).name} | \`${s.condition.op} ${s.condition.value}\` | ${s.forDur} | ${s.noData} |`),
  '',
  '**Queries** (range queries, reduced with `last`, evaluated against the condition above):',
  '',
  ...specs.flatMap((s, i) => [`${i + 1}. ${s.title}`, '', fenced(s.expr), '']),
].join('\n').replace(/\n+$/, '');

const routesTable = (routes) => [
  '| Priority | Slack channel | Contact point | Route matchers | Timing |',
  '|---|---|---|---|---|',
  ...routes.map(r =>
    `| ${r.priorities} | \`${r.channel}\` | \`${r.contactPoint}\` | ` +
    `${r.matchers.map(([k, op, v]) => `\`${k}${op}${v}\``).join(', ')} | ` +
    `wait ${r.groupWait}; update ${r.groupInterval}; repeat ${r.repeatInterval} |`),
].join('\n');
const groupingSentence = (routes) =>
  routes.map(r => `${r.signal} group by \`${r.groupBy.join(', ')}\``).join('; ');

export const buildDocs = ({ specs, routes }) => ({
  'example-alerts.md': `<!-- GENERATED FILE — do not edit. Source: tools/observability/lib/docs.mjs
     (rules table derives from lib/alerts.mjs ALERT_SPECS). Regenerate with:
     node tools/observability/generate-observability.mjs -->

# DKG human-readable Grafana alerting

This generated file is the reproducible source for the dedicated observability
Grafana. Webhook URLs are **secrets** — they live only in Grafana contact points,
never in this repository.

## Human incident contract

- **P1 — CRITICAL:** immediate action; confirmed fleet/service impact or
  telemetry-loss risk.
- **P2 — ACTION:** sustained node/component degradation that needs
  investigation.
- **P3 — WATCH:** no confirmed service impact. Held and grouped as a daily
  metrics-channel post instead of sent in real time.
- Generic ERROR/WARN counts remain useful in dashboards, but do **not** page
  Slack. Rules classify the actual event or operational symptom.
- Every firing message answers: what happened, what is affected, whether to
  react, what to check first, and the evidence. Its single incident link opens
  the relevant panel, node filters and alert time range. Recovery confirms that
  the alert cleared and keeps the same exact link.

## Routing model

${routesTable(routes)}

Routes are appended as children of the root notification policy. Each
signal-specific Slack channel groups by environment, so failures which start
together and recoveries which finish together become one post:
${groupingSentence(routes)}. P3 uses the same grouping for one daily watch post.
Every rule carries \`team=dkg\`, \`signal=<x>\`, \`priority=P1|P2|P3\`,
\`component\`, \`entity_kind\`, and stable \`alert_id\` labels.

The webhooks belong to the Slack app **"DKG Grafana Alerts"** (workspace
OriginTrail) — manage/rotate them at *api.slack.com/apps → DKG Grafana Alerts →
Incoming Webhooks*.

## The ${specs.length} rules

> **Machine-importable copy:** \`alert-rules.provisioning.json\` in this directory
> holds the exact provisioning-API payloads (rules, contact-point templates with
> placeholder webhooks, policy routes). Both it and the dashboard JSONs are
> **generated by \`generate-observability.mjs\`** — edit that script and
> regenerate, never the JSON by hand. The committed payload keeps
> \`<VM_DATASOURCE_UID>\` as a placeholder (instance-specific); render an
> importable copy with
> \`node generate-observability.mjs /tmp/render --vm-uid <your-uid>\`.
> This section is the human explanation.

All queries are **range queries** — on Loki 3.x an *instant* metric query over a
range ≥ a few hours is split internally and dies with \`maximum of series (500)
reached\`; range+reduce avoids that class of failure entirely.

${rulesTable(specs)}

### Design notes

- **Node silent** uses lightweight 15-minute \`absent_over_time\` checks for the
  reviewed production roster, preserving one series per missing node without a
  multi-hour fleet scan. Its fleet-presence guard suppresses a node-by-node
  storm during a total blackout.
- **Fleet blackout** complements it with a separate mainnet-wide P1 rule and
  **noData = Alerting**.
- **Storage overload** classifies the currently observed scheduler/Blazegraph
  timeout signatures instead of counting every unrelated ERROR equally.
- **RPC usage watch** uses an 8k hourly entry level, a recent-usage guard, a
  30-minute pending window, and delayed P3 grouping. This replaces the flapping
  6k real-time rule.
- **Publish failures** require both a failure ratio above 10% and at least five
  publishes, preventing one-of-one low-volume false positives.
- **ACK quorum** uses the bounded terminal outcomes \`timeout|impossible\`.
- **Failover exhausted** filters \`reason="exhausted"\`: the metric contract also
  documents recovery events, which must never page as outages.
- Node-metric and trace rules use **noData OK**, so they cannot pretend the
  signal exists before ingestion is enabled. Query health is checked during
  generation/import; evaluation errors keep the previous state instead of
  becoming false human incidents.

## Re-provisioning from scratch (API recipe)

With an admin session, \`X-Disable-Provenance: true\` header keeps everything
UI-editable:

\`\`\`bash
# 1. Notification template + contact points
PUT  /api/v1/provisioning/templates/dkg-readable

# One contact point per channel; preserve the existing secure webhook URL.
POST /api/v1/provisioning/contact-points
  { "name": "DKG node logs (Slack)", "type": "slack",
    "settings": { "url": "$HOOK_NODE_LOGS" } }          # ×3, one per signal

# 2. Notification policy — ALWAYS GET the tree first and APPEND child routes;
#    a PUT replaces the WHOLE tree and would clobber other teams' routes.
GET  /api/v1/provisioning/policies
PUT  /api/v1/provisioning/policies    # tree + appended routes (matchers above)

# 3. Rules (upsert generated titles, remove the explicit legacy inventory)
POST /api/v1/provisioning/alert-rules # one per rule; folderUID of the
                                      # dashboards folder
PUT  /api/v1/provisioning/folder/dkg-observability/rule-groups/<group>
                                      # 1m incidents, 5m health, 1h P3 watch
\`\`\`

Legacy note: an earlier 4-rule single-channel version of this setup exists on
polaris (Loki 2.5 query shapes — \`level=\` label instead of \`severity_text\`
metadata). The rules above are the current reference.
`,
});
