import {
  ENTITY_SHARE_METADATA_SIDECAR_PREDICATES,
  ENTITY_SHARE_SNAPSHOT_CONTENT_DIGEST_PREDICATE,
  ENTITY_SHARE_SNAPSHOT_MERKLE_ROOT_PREDICATE,
} from '@origintrail-official/dkg-publisher';

/** Agent-local cache annotations; they are not publisher protocol metadata. */
export const SWM_SNAPSHOT_MERKLE_ROOT_PREDICATE =
  ENTITY_SHARE_SNAPSHOT_MERKLE_ROOT_PREDICATE;
export const SWM_SNAPSHOT_CONTENT_DIGEST_PREDICATE =
  ENTITY_SHARE_SNAPSHOT_CONTENT_DIGEST_PREDICATE;

export const SWM_FINALIZATION_ANNOTATION_PREDICATES: ReadonlySet<string> =
  ENTITY_SHARE_METADATA_SIDECAR_PREDICATES;
