export {
  DEFAULT_STORE_BACKEND,
  MANAGED_LOCAL_STORE_BACKEND,
  STORE_BACKENDS,
  getStoreBackendPolicy,
  isExternalBackend as isExternalStoreBackend,
  isKnownStoreBackend,
  isManagedLocalBackend,
  isRetiredStoreBackend,
  isSupportedStoreBackend,
  menuBackendChoices,
  retiredBackendNames,
  storeBackendNames,
  supportedBackendList,
  supportedBackendNames,
  type DefaultStoreBackend,
  type ExternalStoreBackend,
  type LocalStoreBackend,
  type ManagedLocalStoreBackend,
  type MenuStoreBackend,
  type RetiredStoreBackend,
  type StoreBackend,
  type StoreBackendKind,
  type StoreBackendOfKind,
  type StoreBackendPolicy,
  type SupportedStoreBackend,
} from '@origintrail-official/dkg-storage';
